global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0 #5.0 
  publish_frequency: 1.0
  static_map: true
  rolling_window: false

  plugins:
  - {name: static_map,       type: "costmap_2d::StaticLayer"}
  - {name: rgbd_obstacle_layer,     type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflated_layer, type: "costmap_2d::InflationLayer"}

  # static_layer:
  obstacle_layer:
    track_unknown_space: true
  rgbd_obstacle_layer:
    track_unknown_space: true
    voxel_decay: 20   #15
  inflated_layer:
    inflation_radius: 8.0 #4.0      # 1.75 #8.0 worked really well
    cost_scaling_factor: 2.58