global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 2.0 #5.0 
  publish_frequency: 0.0
  static_map: true
  rolling_window: false
  inflater_layer:
    inflation_radius: 2.0 #4.0      # 1.75
    cost_scaling_factor: 2.58
  static_layer:
    track_unknown_space: true
  obstacle_layer:
    track_unknown_space: true
  # plugins: 
  #   - {name: static_map,       type: "costmap_2d::StaticLayer"}
  #   - {name: obstacles,        type: "costmap_2d::VoxelLayer"}
