local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 6.0 #6.0
  height: 6.0 #6.0
  resolution: 0.05
  inflation_radius: 0.1 #0.05     # reduce it according to the tight spaces
  cost_scaling_factor: 10.0 #2.58     #1.5    
