# shutdown_costmaps: false
# controller_frequency: 10.0
# planner_patience: 5.0
# controller_patience: 15.0
# conservative_reset_dist: 3.0
# planner_frequency: 5.0
# oscillation_timeout: 10.0
# oscillation_distance: 0.2

base_global_planner: "navfn/NavfnROS"   #"SBPLLatticePlanner"
base_local_planner: "dwa_local_planner/DWAPlannerROS"
# base_local_planner: "base_local_planner/TrajectoryPlannerROS"
# base_local_planner: "teb_local_planner/TebLocalPlannerROS" #"base_local_planner/TrajectoryPlannerROS"
# recovery_behaviors: [{name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}, 
#                     {name: rotate_recovery, type: rotate_recovery/RotateRecovery},
#                     {name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery}]
# recovery_behaviors: [{name: my_reset, type: moveback_recovery/MovebackRecovery}]
recovery_behaviors: [{name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}, 
                    {name: rotate_recovery, type: rotate_recovery/RotateRecovery},
                    {name: moveback_recovery1, type: moveback_recovery/MovebackRecovery},
                    {name: moveback_recovery2, type: moveback_recovery/MovebackRecovery},
                    {name: moveback_recovery3, type: moveback_recovery/MovebackRecovery}]
controller_frequency: 20.0
planner_patience: 5.0
controller_patience: 15.0
conservative_reset_dist : 3.0
recovery_behavior_enabled: true
clearing_rotation_allowed : true
shutdown_costmaps : false
oscillation_timeout : 5.0
oscillation_distance : 0.5
planner_frequency: 5.0    #0.0 means the global planner will only run when a new goal is received
max_planning_retries : 5