
# for visual servoing controllers
vs_range : [-60, 60, 12, 0.5] # [left angle, right angle, n_steps, settling time]. Angles in degrees, converted to rad in code. 

pid_gains:
  kp : 0.7
  kd : 0.2

# move_towards_object
forward_velocity: 0.1 #m/s
interval_till_restart : 10 # seconds

# head_tilt
head_tilt_angle_search : 10 # degrees
head_tilt_angle_grasp : 30 # degrees



moving_average_n : 10 # for PID settling time
max_graspable_distance: 0.77
mean_err_horiz_alignment : 0.08

recoveries:
  n_scan_attempts : 3

# scene_parser:
time_diff_for_realtime : 0.3 #seconds - for scene parser to determine whether the estimate is live or stale
object_filter:
  height : 0.7
  radius : 2.5

offsets:
  bottle: [0, 0.0, 0.0]
  apple: [0, 0.0, 0.0]
  remote: [0, 0.0, 0.0]
  banana : [0, 0.0, 0.0]
  soda_can : [0, 0.0, 0.0]
  tissue_paper: [-0.0, 0.0, 0.05]
  toothbrush: [-0.0, 0.0, 0.0]
  tie: [-0.0, 0.0, 0.0]
  cell phone: [-0.0, 0.0, 0.0]
  orange: [-0.0, 0.0, 0.0]
  cup: [-0.0, 0.0, 0.0]
  teddy bear: [-0.0, 0.0, 0.0]

contact: 
  bottle: false
  apple: true
  remote: true
  banana: true
  soda_can: false
  tissue_paper: false
  toothbrush: false
  tie: true
  cell phone: true
  orange: false
  cup: false
  teddy bear: false


# FSM params
n_max_servo_attempts: 2
n_max_pick_attempts: 2