wakeword_topic_name: "/interface/wakeword_detector/wakeword"
command_topic_name: "/interface/speech_recognition/command"
engagement_topic_name: "/interface/speech_recognition/engagement"

verbal_response_topic_name: "/interface/response_generator/verbal_response_service"

locations_file: "config/vincentian_2nd_floor.json"
