
base_model: 'yolov8x.pt'
custom_model: '/home/praveen/alfred-autonomy/src/perception/object_detection/model/sodacan_tissue.pt'
# custom_model: '/home/praveen/alfred-autonomy/src/perception/object_detection/model/drawers.pt'

subscribe_topic: '/camera/color/small_image'
# subscribe_topic: '/camera/color/image_raw'

publish_topic: 'object_bounding_boxes'
visualize: true
visualize_topic: 'annotated_image_body'

device_1: 'cuda:0'
device_2: 'cuda:1'

class_list:
  # - 'drawer'
  - 'soda_can'
  - 'tissue_paper'
  - 'toothbrush'
  - 'tie'
  - 'cell_phone'
  - 'banana'
  - 'apple'
  - 'orange'
  - 'bottle'
  - 'cup'
  - 'teddy_bear'
