
base_model: 'yolov8x.pt'
custom_model : '/home/praveen/alfred-autonomy/src/perception/object_detection/model/custom_model/best_new.pt'
# custom_model: '/home/praveen/alfred-autonomy/src/perception/object_detection/model/custom_model/best.pt'
# custom_model: '/home/praveen/alfred-autonomy/src/perception/object_detection/model/drawers.pt'

subscribe_topic: '/camera/color/small_image'
# subscribe_topic: '/camera/color/image_raw'

publish_topic: 'object_bounding_boxes'
visualize: true
visualize_topic: 'annotated_image_body'

device_1: 'cuda:0'
device_2: 'cuda:1'

class_list:
  # - 'drawer'
  - 'soda_can' # 0
  - 'tissue_paper' #1
  - 'toothbrush' #2
  - 'tie' #3
  - 'cell phone' #4
  - 'banana' #5
  - 'apple' #6
  - 'orange' #7
  - 'bottle' #8
  - 'cup' #9
  - 'teddy bear' #10
  - 'remote' #11
