
base_model: 'yolov8x.pt'
custom_model: '/home/praveen/alfred-autonomy/src/perception/object_detection/model/sodacan_tissue.pt'

# subscribe_topic: '/camera/color/small_image'
subscribe_topic: '/camera/color/small_image'

publish_topic: 'object_bounding_boxes'
visualize: true
visualize_topic: 'annotated_image_body'

device: 'cuda:0'